services:
  - type: web
    name: challenge-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: DB_URL
        sync: false 