services:
  - type: web
    name: challenge-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: DB_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true 